<?xml version="1.0" encoding="UTF-8"?> 

<!-- Declaracion DTD --> 
<!DOCTYPE Musica [ 
<!ELEMENT Musica (album)> 
<!ELEMENT album (titulo, grupo, year?, single?)> 
<!ELEMENT titulo (#PCDATA)> 
<!ELEMENT grupo (#PCDATA)> 
<!ELEMENT year (#PCDATA)> 
<!ELEMENT single (EMPTY)>   

<!-- Definicion de los Atributos --> 
<!ATTLIST album formato (cd|cassete|vinilo|mp3) ID #REQUIRED>
<!ATTLIST album idioma (en|es) ID #IMPLIED>
]>

<!-- Documento XML -->
<Musica>
    <album>
        <titulo formato="cd" idioma="en">Violator</titulo>
        <grupo>Depeche Mode</grupo>
        <year>1990</year>
        <single>Personal Jesus</single>
        <single>Enjoy de Silence</single>
        <single>Policy of truth</single>
        <single>World in my eyes</single>
    </album>

    <album>
        <titulo formato="cd" idioma="en">OK Computer</titulo>
        <grupo>Radiohead</grupo>
        <year>1997</year>
        <single>Paranoid Android</single>
        <single>Karma Police</single>
        <single>No surprises</single>
    </album>

    <album>
        <titulo formato="vinilo" idioma="es">Como la cabeza al sombrero</titulo>
        <grupo>El Ãºltimo de la fila</grupo>
        <year>1988</year>
        <single/>
    </album>

    <album>
        <titulo formato="mp3" idioma="es">Hacia lo salvaje</titulo>
        <grupo>Amaral</grupo>
        <year>2011</year>
        <single>Hacia lo salvaje</single>
        <single>Cuando suba la marea</single>
        <single>Hoy es el principio del final</single>
    </album>

</Musica>
        
